### Command for Installing Libraries

In [1]:
!pip install pandas scikit-learn xgboost joblib

Requirement already satisfied: pandas in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.7.2)
Requirement already satisfied: xgboost in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.1.1)
Requirement already satisfied: joblib in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.23.2 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\mubas\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Importing Libraries

In [113]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.model_selection import train_test_split
import joblib

In [114]:
df=pd.read_csv('job_salary_prediction_dataset.csv')

In [115]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [117]:
df["job_title"].value_counts()

job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64

### One Hote Encoding

In [118]:
encoder=OneHotEncoder(dtype=int)

In [119]:
encoded_matrix = encoder.fit_transform(df[['job_title','education_level','industry','company_size','location','remote_work']]).toarray()

encoded_dataframe = pd.DataFrame(encoded_matrix, columns=encoder.get_feature_names_out())

In [120]:
encoded_dataframe.head(1)

,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [121]:
numeric_only_columns_dataframe=df[["experience_years","skills_count","certifications","salary"]]

In [122]:
df_final = pd.concat([numeric_only_columns_dataframe, encoded_dataframe], axis=1)

In [123]:
df_final

,experience_years,skills_count,certifications,salary,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,10,2,2,109413,1,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,5,17,0,93764,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,18,4,1,148123,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
3,19,13,0,189123,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,15,7,0,165069,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,17,2,1,127791,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
249996,20,7,2,154593,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
249997,1,12,0,75988,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
249998,0,2,5,90467,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
249999,16,2,5,133084,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,1,0

### Divide Data in Input And Target Variables

In [124]:
X=df_final.drop(columns=["salary"])
y=df["salary"]

### Spliting data into training and testing data

In [125]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

### Save the Columns Order For model Prediction

In [ ]:
columns_for_input=X_train.columns
joblib.dump(columns_for_input,"Columns.joblib")

In [ ]:
model=XGBRegressor(	random_state=1)

### Training Model

In [ ]:
model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_pred=model.predict(X_test)
mean_absolute_error(y_test,y_pred)

4321.99560546875

In [ ]:
r2_score(y_test,y_pred)

0.9788591265678406

### Dumping the Model And Encoder For Prediction in Web App

In [ ]:
joblib.dump(model,"model.joblib")
joblib.dump(encoder,"encoder.joblib")

['encoder.joblib']

## Prediction  (Draft for Web App)

In [132]:
input=df.sample(1)
input_row=input.copy()

In [133]:
input_row=input_row.drop(columns=["salary","experience_years","skills_count","certifications"])

In [134]:
input_row

,job_title,education_level,industry,company_size,location,remote_work
58730,Cloud Engineer,Bachelor,Media,Small,India,Hybrid

In [135]:
input_row_encoded=encoder.transform(input_row).toarray()
input_row_encoded

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0]])

In [136]:
columns=encoder.get_feature_names_out()

B=pd.DataFrame(input_row_encoded,columns=columns)
B

,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [137]:
c=input[['experience_years',"skills_count","certifications"]]
c

       experience_years  skills_count  certifications
58730                 0             2               3

In [138]:

final = pd.concat([B.reset_index(drop=True), c.reset_index(drop=True)], axis=1)

In [139]:
final

,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,...,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes,experience_years,skills_count,certifications
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,2,3

In [141]:
final_data=final.reindex(columns=columns_for_input, fill_value=0)

In [142]:
final_data

,experience_years,skills_count,certifications,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,0,2,3,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [143]:
prediction=model.predict(final_data)
print(prediction[0])

67169.1